<?= $this->extend('layout/main') ?>

<?= $this->section('content') ?>
<div class="card col-md-6 mx-auto">
    <div class="card-header border-secondary">
        <i class="fas fa-file-upload me-2"></i> Process System Audit
    </div>
    <div class="card-body">
        <p class="text-secondary small">Upload the JSON file generated by the WinAudit Go Agent.</p>
        <form action="/upload/process" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label class="form-label">Audit JSON File</label>
                <input type="file" name="audit_file" class="form-control bg-dark text-light border-secondary" accept=".json" required>
            </div>
            <div class="d-grid">
                <button type="submit" class="btn btn-primary"><i class="fas fa-check-circle me-2"></i> Process Audit</button>
            </div>
        </form>
    </div>
</div>
<?= $this->endSection() ?>
